# A dockerized badgr-server stack for development
version: '3.3'
services:

  # this container mirrors in the app code and runs the django dev server
  api:
    # build:
    #   context: .
    #   dockerfile: .docker/Dockerfile.dev.api
    image: mint-o-badges:dev
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    command: /badgr_server/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./apps:/badgr_server/apps
      - ./manage.py:/badgr_server/manage.py
      # - ./.docker/etc/settings_local.dev.py:/badgr_server/apps/mainsite/settings_local.py
      - ./settings_local.py:/badgr_server/apps/mainsite/settings_local.py
    networks:
      - badgr
    ports:
      - "8000:8000"

  # this container runs memcached
  memcached:
    image: 'bitnami/memcached:latest'
    expose:
      - "11211"
    networks:
      - badgr

  # this container runs mysql (database)
  db:
    image: mysql:5.6.39
    # platform: linux/amd64 comment in if you are on Apple Silicon
    volumes:
      - badgr_server_dev_db:/var/lib/mysql:rw
      - ./.docker/etc/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_HOST=db"
      - "MYSQL_ROOT_PASSWORD=password"
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 25
    networks:
      - badgr

networks:
  badgr:
    driver: bridge

volumes:
  badgr_server_dev_db: