# Generated by Django 3.2 on 2025-07-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badgeuser", "0027_alter_badgeuser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeuser",
            name="secure_password_set",
            field=models.BooleanField(default=False),
        ),
    ]
