# Generated by Django 3.2 on 2025-07-31 07:38

from django.db import migrations, models
from badgeuser.models import BadgeUser


def update_existing_users(apps, schema_editor):
    """
    Set secure_password_set field to false for existing users
    """
    BadgeUser.objects.all().update(secure_password_set=False)


def reverse_update_users(apps, schema_editor):
    """Reverse operation - field didn't exist before, so no action needed"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("badgeuser", "0027_alter_badgeuser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeuser",
            name="secure_password_set",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(update_existing_users, reverse_update_users),
    ]
