# Generated by Django 3.2 on 2025-08-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0028_badgeuser_secure_password_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeuser',
            name='secure_password_set',
            field=models.BooleanField(default=True),
        ),
    ]
