# Generated by Django 3.2 on 2025-09-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0029_userpreference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'key')},
        ),
    ]
