# Generated by Django 3.2 on 2025-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0029_userpreference_squashed_0030_alter_userpreference_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
