# Generated by Django 3.2 on 2025-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0030_badgeuser_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeuser',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
