# Generated by Django 3.2 on 2025-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0037_auto_20171113_1015_squashed_0081_auto_20250903_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='linkedinId',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
