# Generated by Django 3.2 on 2025-09-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0037_auto_20171113_1015_squashed_0081_auto_20250903_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkextension',
            name='network',
        ),
        migrations.RemoveField(
            model_name='networkinvite',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='networkinvite',
            name='network',
        ),
        migrations.AlterUniqueTogether(
            name='networkstaff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='networkstaff',
            name='network',
        ),
        migrations.RemoveField(
            model_name='networkstaff',
            name='user',
        ),
        migrations.AlterField(
            model_name='issuer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='NetworkExtension',
        ),
        migrations.DeleteModel(
            name='NetworkInvite',
        ),
        migrations.DeleteModel(
            name='NetworkStaff',
        ),
    ]
