# Generated by Django 3.2 on 2025-09-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0038_issuer_linkedinid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='networkextension',
            name='network',
        ),
        migrations.AlterUniqueTogether(
            name='networkstaff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='networkstaff',
            name='network',
        ),
        migrations.RemoveField(
            model_name='networkstaff',
            name='user',
        ),
        migrations.AddField(
            model_name='issuer',
            name='is_network',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='networkinvite',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='issuer.issuer'),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='NetworkExtension',
        ),
        migrations.DeleteModel(
            name='NetworkStaff',
        ),
        migrations.AddField(
            model_name='networkmembership',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_memberships', to='issuer.issuer'),
        ),
        migrations.AddField(
            model_name='networkmembership',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='issuer.issuer'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='networks',
            field=models.ManyToManyField(related_name='_issuer_issuer_networks_+', through='issuer.NetworkMembership', to='issuer.Issuer'),
        ),
        migrations.AlterUniqueTogether(
            name='networkmembership',
            unique_together={('network', 'issuer')},
        ),
    ]
