# Generated by Django 3.2 on 2025-09-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0038_auto_20250905_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='is_network',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NetworkMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.ForeignKey(limit_choices_to={'is_network': False}, on_delete=django.db.models.deletion.CASCADE, related_name='network_memberships', to='issuer.issuer')),
                ('network', models.ForeignKey(limit_choices_to={'is_network': True}, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='issuer.issuer')),
            ],
            options={
                'unique_together': {('network', 'issuer')},
            },
        ),
        migrations.AddField(
            model_name='issuer',
            name='networks',
            field=models.ManyToManyField(limit_choices_to={'is_network': True}, related_name='_issuer_issuer_networks_+', through='issuer.NetworkMembership', to='issuer.Issuer'),
        ),
    ]
