# Generated by Django 3.2 on 2025-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0039_auto_20250905_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
