# Generated by Django 3.2 on 2025-09-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0039_auto_20250923_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeClassNetworkShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('badgeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_shares', to='issuer.badgeclass')),
                ('network', models.ForeignKey(limit_choices_to={'is_network': True}, on_delete=django.db.models.deletion.CASCADE, related_name='shared_badges', to='issuer.issuer')),
                ('shared_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge Class Network Share',
                'verbose_name_plural': 'Badge Class Network Shares',
                'unique_together': {('badgeclass', 'network')},
            },
        ),
    ]
