# Generated by Django 3.2 on 2025-10-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0040_badgeclassnetworkshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclassnetworkshare',
            name='shared_by_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_shares_created', to='issuer.issuer'),
        ),
    ]
