# Generated by Django 3.2 on 2025-09-11 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0040_issuer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('invitedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('acceptedOn', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Revoked', 'Revoked')], default='Pending', max_length=254)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issuer.issuer')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='issuer.issuer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
