# Generated by Django 3.2 on 2025-10-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0041_badgeclassnetworkshare_shared_by_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='activity_end_date',
            field=models.DateTimeField(blank=True, default=None, help_text='The datetime the activity/course ended', null=True),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='activity_start_date',
            field=models.DateTimeField(blank=True, default=None, help_text='The datetime the activity/course started', null=True),
        ),
    ]
