# Generated by Django 3.2 on 2025-09-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0041_networkinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='networks',
            field=models.ManyToManyField(related_name='_issuer_issuer_networks_+', through='issuer.NetworkMembership', to='issuer.Issuer'),
        ),
    ]
