# Generated by Django 3.2 on 2025-10-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0042_auto_20251020_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='activity_end_date',
            field=models.DateTimeField(blank=True, default=None, help_text='The datetime the activity/course ended', null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='activity_start_date',
            field=models.DateTimeField(blank=True, default=None, help_text='The datetime the activity/course started', null=True),
        ),
    ]
