# Generated by Django 3.2 on 2025-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0043_auto_20251021_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='activity_city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='activity_online',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='activity_zip',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='activity_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='activity_online',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='activity_zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
