# Generated by Django 3.2 on 2025-11-12 17:03

from django.db import migrations, models


def migrate_expiration(apps, schema_editor):
    BadgeClass = apps.get_model("issuer", "BadgeClass")
    duration_map = {
        "days": 1,
        "weeks": 7,
        "months": 30,
        "years": 365,
    }

    for badge in BadgeClass.objects.all():
        if badge.expires_amount and badge.expires_duration:
            multiplier = duration_map.get(badge.expires_duration, 0)
            badge.expiration = badge.expires_amount * multiplier
            badge.save()


def reverse_migrate_expiration(apps, schema_editor):
    BadgeClass = apps.get_model("issuer", "BadgeClass")

    for badge in BadgeClass.objects.exclude(expiration__isnull=True):
        badge.expires_amount = badge.expiration
        badge.expires_duration = "days"
        badge.save()


class Migration(migrations.Migration):
    dependencies = [
        ("issuer", "0044_auto_20251107_0310"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeclass",
            name="expiration",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Number of days the badge is valid after being issued.",
                null=True,
            ),
        ),
        migrations.RunPython(migrate_expiration),
        migrations.RemoveField(
            model_name="badgeclass",
            name="expires_amount",
        ),
        migrations.RemoveField(
            model_name="badgeclass",
            name="expires_duration",
        ),
    ]
