# Generated by Django 3.2 on 2025-11-14 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0045_auto_20251112_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='expiration',
            field=models.IntegerField(blank=True, default=None, help_text='Number of days the badge is valid after being issued.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36500)]),
        ),
    ]
