# Generated by Django 5.2.8 on 2025-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0046_alter_badgeclass_expiration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='badgeinstance',
            new_name='issuer_badg_recipie_6a2cd8_idx',
            old_fields=('recipient_identifier', 'badgeclass', 'revoked'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='networks',
            field=models.ManyToManyField(related_name='partner_issuers', through='issuer.NetworkMembership', to='issuer.issuer'),
        ),
    ]
