# Generated by Django 5.2.8 on 2025-12-09 13:53

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0047_rename_badgeinstance_recipient_identifier_badgeclass_revoked_issuer_badg_recipie_6a2cd8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='evidence_items',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
