# Generated by Django 5.2.8 on 2026-01-20 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0051_qrcode_evidence_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='limit_account_level',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=254),
        ),
        migrations.AddField(
            model_name='issuer',
            name='limit_accounts_admin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Admin Accounts'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='limit_accounts_member',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Member Accounts'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='limit_aiskills_requests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='AI Tool Requests'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='limit_badge_award',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Award Badges'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='limit_badge_create',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create Badges'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='limit_learningpaths_create',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create Learningpaths'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='limit_pdfeditor',
            field=models.BooleanField(blank=True, null=True, verbose_name='PDF Editor'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='limit_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Period start'),
        ),
    ]
