# Generated by Django 5.2.8 on 2026-01-22 08:08

import django.utils.timezone
import issuer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0051_qrcode_evidence_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='quota_account_level',
            field=models.CharField(blank=True, choices=issuer.models.Issuer.get_quota_choices, default=issuer.models.Issuer.get_quota_default, max_length=254, null=True, verbose_name='Account Level'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_accounts_admin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Admin Accounts'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_accounts_member',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Member Accounts'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_aiskills_requests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='AI Tool Requests'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_badge_award',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Award Badges'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_badge_create',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create Badges'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_learningpath_create',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create Learningpaths'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_pdfeditor',
            field=models.BooleanField(blank=True, null=True, verbose_name='PDF Editor'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='quota_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Period start'),
        ),
    ]
