# Generated by Django 5.2.8 on 2026-01-10 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0051_qrcode_evidence_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeClassArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254)),
                ('badgeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.badgeclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
