# Generated by Django 3.2 on 2024-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0064_auto_20211122_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='imageFrame',
            field=models.BooleanField(default=False),
        ),
    ]
