# Generated by Django 3.2 on 2024-08-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0067_auto_20240816_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254)),
                ('learningPath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.learningpath')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
