# Generated by Django 3.2 on 2024-08-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0067_auto_20240819_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathbadge',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
