# Generated by Django 3.2 on 2024-09-02 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0067_learningpath_learningpathbadge_learningpathparticipant_learningpathtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='participationBadge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.badgeclass'),
        ),
    ]
