# Generated by Django 3.2 on 2024-08-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0068_learningpathtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningpathbadge',
            options={},
        ),
        migrations.RenameField(
            model_name='learningpathbadge',
            old_name='learninPath',
            new_name='learning_path',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='badges',
        ),
        migrations.AlterUniqueTogether(
            name='learningpathbadge',
            unique_together=set(),
        ),
    ]
