# Generated by Django 3.2 on 2024-08-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0068_learningpathtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='badges',
            field=models.ManyToManyField(through='issuer.LearningPathBadge', to='issuer.BadgeClass'),
        ),
    ]
