# Generated by Django 3.2 on 2024-09-16 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0068_requestedlearningpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpathparticipant',
            name='completed_badges',
        ),
        migrations.AddField(
            model_name='learningpathparticipant',
            name='completed_badges',
            field=models.ManyToManyField(blank=True, to='issuer.BadgeClass'),
        ),
        migrations.CreateModel(
            name='LearningPathInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('issued_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_identifier', models.CharField(db_index=True, max_length=768)),
                ('slug', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('revocation_reason', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.issuer')),
                ('learningPath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learningpath_instances', to='issuer.learningpath')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
