# Generated by Django 2.2.28 on 2024-03-03 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0068_auto_20240222_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBadgeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('source', models.CharField(default='local', max_length=254)),
                ('source_url', models.CharField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('issued_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_identifier', models.CharField(db_index=True, max_length=768)),
                ('recipient_type', models.CharField(choices=[('email', 'email'), ('openBadgeId', 'openBadgeId'), ('telephone', 'telephone'), ('url', 'url')], default='email', max_length=255)),
                ('image', models.FileField(blank=True, upload_to='uploads/badges')),
                ('slug', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('revocation_reason', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('acceptance', models.CharField(choices=[('Unaccepted', 'Unaccepted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Unaccepted', max_length=254)),
                ('hashed', models.BooleanField(default=True)),
                ('salt', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('collectionbadgeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionbadgeinstances', to='issuer.CollectionBadgeContainer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('recipient_identifier', 'collectionbadgeclass', 'revoked')},
            },
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
    ]
