# Generated by Django 3.2 on 2024-09-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_auto_20200608_0452'),
        ('issuer', '0068_alter_learningpath_participationbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='badgrapp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.badgrapp'),
        ),
    ]
