# Generated by Django 3.2 on 2024-09-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0070_auto_20240902_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
