# Generated by Django 3.2 on 2024-09-02 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0071_learningpath_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.date),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badgeinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.date(2024, 9, 2)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
