# Generated by Django 3.2 on 2025-04-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0072_auto_20250410_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedbadgeassertion',
            name='acceptance',
            field=models.CharField(choices=[('Unaccepted', 'Unaccepted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Unaccepted', max_length=254),
        ),
    ]
