# Generated by Django 3.2 on 2025-04-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0073_importedbadgeassertion_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedbadgeassertion',
            name='source',
            field=models.CharField(default='local', max_length=254),
        ),
        migrations.AddField(
            model_name='importedbadgeassertion',
            name='source_url',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
