# Generated by Django 3.2 on 2025-04-02 15:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0074_badgeinstance_ob_json_2_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='customCriteria',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
