# Generated by Django 3.2 on 2025-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0075_badgeclass_customcriteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeclass',
            name='customCriteria',
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='criteria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
