# Generated by Django 3.2 on 2025-05-13 08:31

from django.db import migrations, models
import issuer.utils


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0076_badgeclass_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='ob_json_3_0',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='private_key',
            field=models.CharField(blank=True, default=issuer.utils.generate_private_key_pem, max_length=512, null=True),
        ),
    ]
