# Generated by Django 3.2 on 2025-07-04 05:38

from django.db import migrations, models
from issuer.models import LearningPath, LearningPathBadge


def set_required_badges_count(apps, schema_editor):
    for lp in LearningPath.objects.all():
        badge_count = LearningPathBadge.objects.filter(learning_path=lp).count()
        lp.required_badges_count = badge_count
        lp.save()


class Migration(migrations.Migration):
    dependencies = [
        ("issuer", "0077_auto_20250513_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="required_badges_count",
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.RunPython(set_required_badges_count),
    ]
