# Generated by Django 3.2 on 2025-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0078_learningpath_required_badges_count_squashed_0079_learningpath_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
