# Generated by Django 3.2 on 2025-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issuer", "0078_learningpath_required_badges_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="activated",
            field=models.BooleanField(default=True),
        ),
    ]
