# Generated by Django 3.2 on 2025-08-21 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import issuer.utils
import mainsite.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0026_iframeurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0079_alter_learningpath_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('source', models.CharField(default='local', max_length=254)),
                ('source_url', models.CharField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('slug', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/issuers')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=254, null=True)),
                ('private_key', models.CharField(blank=True, default=issuer.utils.generate_private_key_pem, max_length=512, null=True)),
                ('state', models.CharField(blank=True, max_length=254, null=True)),
                ('badgrapp', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.badgrapp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(mainsite.mixins.ResizeUploadedImage, mainsite.mixins.ScrubUploadedSvgImage, mainsite.mixins.PngImagePreview, models.Model),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='country',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='NetworkStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('staff', 'Staff')], default='staff', max_length=254)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('network', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NetworkInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('invitedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Revoked', 'Revoked')], default='Pending', max_length=254)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issuer.issuer')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='issuer.network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='network',
            name='partner_issuers',
            field=models.ManyToManyField(blank=True, related_name='networks', to='issuer.Issuer'),
        ),
        migrations.AddField(
            model_name='network',
            name='staff',
            field=models.ManyToManyField(through='issuer.NetworkStaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='network',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
