# Generated by Django 3.2 on 2025-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0080_auto_20250820_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinvite',
            name='acceptedOn',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
