# Generated by Django 3.2 on 2025-09-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0080_auto_20250824_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='recipient_identifier',
            field=models.CharField(db_index=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='importedbadgeassertion',
            name='recipient_identifier',
            field=models.CharField(db_index=True, max_length=320),
        ),
    ]
