-- shrink some indices to not run into issues with their size
ALTER TABLE `account_emailaddress` MODIFY email VARCHAR(191);
ALTER TABLE `backpack_backpackcollection` MODIFY entity_id VARCHAR(191);
ALTER TABLE `badgeuser_userrecipientidentifier` MODIFY identifier VARCHAR(191);
ALTER TABLE `badgrsocialauth_saml2account` MODIFY uuid VARCHAR(191);
ALTER TABLE `celery_results_taskresult` MODIFY task_id VARCHAR(191);
ALTER TABLE `celery_results_taskresult` MODIFY task_id VARCHAR(191);
ALTER TABLE `externaltools_externaltool` MODIFY entity_id VARCHAR(191);
ALTER TABLE `issuer_badgeclass` MODIFY entity_id VARCHAR(191);
ALTER TABLE `issuer_badgeclass` MODIFY slug VARCHAR(191);
ALTER TABLE `issuer_badgeclass` MODIFY source_url VARCHAR(191);
ALTER TABLE `issuer_badgeclasstag` MODIFY name VARCHAR(191);
ALTER TABLE `issuer_badgeinstance` MODIFY entity_id VARCHAR(191);
ALTER TABLE `issuer_badgeinstance` MODIFY recipient_identifier VARCHAR(191);
ALTER TABLE `issuer_badgeinstance` MODIFY slug VARCHAR(191);
ALTER TABLE `issuer_badgeinstance` MODIFY source_url VARCHAR(191);
ALTER TABLE `issuer_issuer` MODIFY entity_id VARCHAR(191);
ALTER TABLE `issuer_issuer` MODIFY slug VARCHAR(191);
ALTER TABLE `issuer_issuer` MODIFY source_url VARCHAR(191);
ALTER TABLE `issuer_issuerstaffrequest` MODIFY entity_id VARCHAR(191);
ALTER TABLE `issuer_learningpath` MODIFY entity_id VARCHAR(191);
ALTER TABLE `issuer_learningpath` MODIFY slug VARCHAR(191);
ALTER TABLE `issuer_learningpathtag` MODIFY name VARCHAR(191);
ALTER TABLE `issuer_qrcode` MODIFY entity_id VARCHAR(191);
ALTER TABLE `issuer_requestedbadge` MODIFY entity_id VARCHAR(191);
ALTER TABLE `issuer_requestedlearningpath` MODIFY entity_id VARCHAR(191);
ALTER TABLE `mainsite_accesstokenscope` MODIFY scope VARCHAR(191);
ALTER TABLE `mainsite_badgrapp` MODIFY cors VARCHAR(191);
ALTER TABLE `mainsite_emailblacklist` MODIFY email VARCHAR(191);
ALTER TABLE `oauth2_provider_accesstoken` MODIFY token VARCHAR(191);
ALTER TABLE `oauth2_provider_application` MODIFY client_secret VARCHAR(191);
ALTER TABLE `oauth2_provider_grant` MODIFY code VARCHAR(191);
ALTER TABLE `oauth2_provider_refreshtoken` MODIFY token VARCHAR(191);
ALTER TABLE `users` MODIFY entity_id VARCHAR(191);

-- modify the database itself
ALTER DATABASE badgr CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- change collation
ALTER TABLE `account_emailaddress` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `account_emailconfirmation` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `auth_group` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `auth_group_permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `auth_permission` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `authtoken_token` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `backpack_backpackbadgeshare` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `backpack_backpackcollection` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `backpack_backpackcollectionbadgeinstance` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `backpack_backpackcollectionshare` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `badgeuser_emailaddressvariant` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `badgeuser_termsagreement` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `badgeuser_termsversion` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `badgeuser_userrecipientidentifier` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `badgrsocialauth_saml2account` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `badgrsocialauth_saml2configuration` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `celery_results_taskresult` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `django_admin_log` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `django_content_type` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `django_migrations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `django_session` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `django_site` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `externaltools_externaltool` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `externaltools_externaltoollaunchpoint` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `externaltools_externaltooluseractivation` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_badgeclass` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_badgeclassalignment` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_badgeclassextension` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_badgeclasstag` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_badgeinstance` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_badgeinstancebakedimage` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_badgeinstanceevidence` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_badgeinstanceextension` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_importedbadgeassertion` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_importedbadgeassertionextension` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_issuer` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_issuerextension` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_issuerstaff` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_issuerstaffrequest` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_learningpath` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_learningpathbadge` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_learningpathtag` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_qrcode` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_requestedbadge` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `issuer_requestedlearningpath` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `mainsite_accesstokenscope` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `mainsite_altchachallenge` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `mainsite_applicationinfo` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `mainsite_badgrapp` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `mainsite_emailblacklist` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `oauth2_provider_accesstoken` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `oauth2_provider_application` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `oauth2_provider_grant` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `oauth2_provider_refreshtoken` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `socialaccount_socialaccount` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `socialaccount_socialapp` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `socialaccount_socialapp_sites` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `socialaccount_socialtoken` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `users_groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `users_user_permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- reset the indices to 255
ALTER TABLE `account_emailaddress` MODIFY email VARCHAR(255);
ALTER TABLE `backpack_backpackcollection` MODIFY entity_id VARCHAR(255);
ALTER TABLE `badgeuser_userrecipientidentifier` MODIFY identifier VARCHAR(255);
ALTER TABLE `badgrsocialauth_saml2account` MODIFY uuid VARCHAR(255);
ALTER TABLE `celery_results_taskresult` MODIFY task_id VARCHAR(255);
ALTER TABLE `celery_results_taskresult` MODIFY task_id VARCHAR(255);
ALTER TABLE `externaltools_externaltool` MODIFY entity_id VARCHAR(255);
ALTER TABLE `issuer_badgeclass` MODIFY entity_id VARCHAR(255);
ALTER TABLE `issuer_badgeclass` MODIFY slug VARCHAR(255);
ALTER TABLE `issuer_badgeclass` MODIFY source_url VARCHAR(255);
ALTER TABLE `issuer_badgeclasstag` MODIFY name VARCHAR(255);
ALTER TABLE `issuer_badgeinstance` MODIFY entity_id VARCHAR(255);
ALTER TABLE `issuer_badgeinstance` MODIFY recipient_identifier VARCHAR(255);
ALTER TABLE `issuer_badgeinstance` MODIFY slug VARCHAR(255);
ALTER TABLE `issuer_badgeinstance` MODIFY source_url VARCHAR(255);
ALTER TABLE `issuer_issuer` MODIFY entity_id VARCHAR(255);
ALTER TABLE `issuer_issuer` MODIFY slug VARCHAR(255);
ALTER TABLE `issuer_issuer` MODIFY source_url VARCHAR(255);
ALTER TABLE `issuer_issuerstaffrequest` MODIFY entity_id VARCHAR(255);
ALTER TABLE `issuer_learningpath` MODIFY entity_id VARCHAR(255);
ALTER TABLE `issuer_learningpath` MODIFY slug VARCHAR(255);
ALTER TABLE `issuer_learningpathtag` MODIFY name VARCHAR(255);
ALTER TABLE `issuer_qrcode` MODIFY entity_id VARCHAR(255);
ALTER TABLE `issuer_requestedbadge` MODIFY entity_id VARCHAR(255);
ALTER TABLE `issuer_requestedlearningpath` MODIFY entity_id VARCHAR(255);
ALTER TABLE `mainsite_accesstokenscope` MODIFY scope VARCHAR(255);
ALTER TABLE `mainsite_badgrapp` MODIFY cors VARCHAR(255);
ALTER TABLE `mainsite_emailblacklist` MODIFY email VARCHAR(255);
ALTER TABLE `oauth2_provider_accesstoken` MODIFY token VARCHAR(255);
ALTER TABLE `oauth2_provider_application` MODIFY client_secret VARCHAR(255);
ALTER TABLE `oauth2_provider_grant` MODIFY code VARCHAR(255);
ALTER TABLE `oauth2_provider_refreshtoken` MODIFY token VARCHAR(255);
ALTER TABLE `users` MODIFY entity_id VARCHAR(255);