# Generated by Django 3.2 on 2024-05-14 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
        ('mainsite', '0025_accesstokensessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstokensessionid',
            name='id',
        ),
        migrations.AlterField(
            model_name='accesstokensessionid',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
        ),
    ]
