# Generated by Django 3.2 on 2024-06-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0026_auto_20240514_0502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessTokenSessionId',
        ),
    ]
