# Generated by Django 3.2 on 2025-07-10 10:35

from django.db import migrations, models
from backpack.models import BackpackCollection


def generate_permanent_hashes(apps, schema_editor):
    import binascii
    import os

    for collection in BackpackCollection.objects.all():
        while True:
            hash_value = str(binascii.hexlify(os.urandom(16)), "utf-8")
            if not BackpackCollection.objects.filter(
                permanent_hash=hash_value
            ).exists():
                collection.permanent_hash = hash_value
                collection.save()
                break


def reverse_generate_permanent_hashes(apps, schema_editor):
    BackpackCollection.objects.update(permanent_hash="")


class Migration(migrations.Migration):
    dependencies = [
        ("backpack", "0013_auto_20200608_0452"),
    ]

    operations = [
        migrations.AddField(
            model_name="backpackcollection",
            name="permanent_hash",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(
            generate_permanent_hashes,
            reverse_generate_permanent_hashes,
        ),
    ]
