# Generated by Django 3.2 on 2025-10-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('issuer', '0041_badgeclassnetworkshare_shared_by_issuer'),
        ('backpack', '0013_auto_20200608_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backpackcollectionbadgeinstance',
            name='badgeinstance',
        ),
        migrations.AddField(
            model_name='backpackcollectionbadgeinstance',
            name='badgeinstance_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_instances', to='issuer.badgeinstance'),
        ),
        migrations.AddField(
            model_name='backpackcollectionbadgeinstance',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='backpackcollectionbadgeinstance',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
