# Generated by Django 3.2 on 2025-10-16 13:48

from django.db import migrations


def populate_content_type(apps, schema_editor):
    BackpackCollectionBadgeInstance = apps.get_model(
        "backpack", "BackpackCollectionBadgeInstance"
    )
    BadgeInstance = apps.get_model("issuer", "BadgeInstance")
    ContentType = apps.get_model("contenttypes", "ContentType")

    badge_content_type = ContentType.objects.get_for_model(BadgeInstance)

    for collection_badge in BackpackCollectionBadgeInstance.objects.filter(
        content_type__isnull=True
    ):
        collection_badge.content_type = badge_content_type
        collection_badge.object_id = str(collection_badge.badgeinstance_fk_id)
        collection_badge.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backpack", "0014_auto_20251016_0647"),
    ]

    operations = [
        migrations.RunPython(populate_content_type),
    ]
