# Generated by Django 3.2 on 2025-07-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0014_backpackcollection_permanent_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpackcollection',
            name='permanent_hash',
            field=models.CharField(blank=True, default='1f3e9c300502f228b5fb2bf04f550f09', max_length=254, unique=True),
        ),
    ]
