# Generated by Django 3.2 on 2025-10-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backpack', '0015_populate_collection_badge_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpackcollectionbadgeinstance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='backpackcollectionbadgeinstance',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
